CREATE TABLE IF NOT EXISTS PRICES (
  PRICE_LIST INTEGER AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID  BIGINT NULL,
  START_DATE TIMESTAMP NULL,
  END_DATE TIMESTAMP NULL,
  PRODUCT_ID BIGINT NULL,
  PRIORITY INTEGER NULL,
  PRICE FLOAT(53) NULL,
  CURRENCY VARCHAR(250) NULL,
  LAST_UPDATE TIMESTAMP NULL,
  LAST_UPDATE_BY VARCHAR(250) NULL
 );